version: '3.8'

services:
  postgres:
      image: postgres:latest
      container_name: postgres
      environment:
        POSTGRES_DB: practice
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: root
      ports:
        - "5433:5432"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  django:
    build: .
    container_name: django
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  celery:
    build: .
    container_name: celery
    command: celery -A ErrorHandling worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - django
      - rabbitmq
  
  start_consumers:
    build: .
    container_name: start_consumers
    command: python manage.py start_consumers
    volumes:
      - .:/app
    depends_on:
      - django
      - rabbitmq
